### PR TITLE
Auto generetate onConflict clause for upserts

### PR DESCRIPTION
**Pull request by lauri865**
Upserts with multiple primary keys need explicit onConflict clause which we can generate from the primaryKeys parameter.

### CODE REVIEW

**Review by psteinroe — CHANGES_REQUESTED** [review]
hey @lauri865, thanks for the contribution! can you make this change in `buildUpsertFetcher` instead?

**Comment by psteinroe** [comment]
also, can you point me to a documentation here? I have never encountered this issue.

**Comment by psteinroe** [comment]
and we need a changeset

**Comment by lauri865** [comment]
I initially did, but for some reason I changed it to use-upsert level. I think thee may have been discrepancies between swc and supabase. But will double check, as I did it quickly and not familiar with the codebase yet.

It's a postgres thing. Don't know exact docs, but speaking from experience, see e.g.:
https://stackoverflow.com/a/38066008

**Comment by lauri865** [comment]
@psteinroe, added the necessary changes + updated supabase package versions.

A few notions:
1. The `opts` parameter carries around `react-query` options to `supabase`. There's no splitting or sanitisation happening it seems, but I don't understand why types don't catch that (don't have too much time to dig now). In general, I think what's much better to add supabase options under e.g. `opts.postgrestOptions` or `opts.clientQueryOptions` or equivalent. To easily type and split them. From experience, inlining two configs is often more work that it's worth, and becomes brittle easily.
2. I'm not sure how I feel about version pinning for `@supabase/postgrest-js` & `@supabase/supabase-js` – if you wan't to use the latest Supabase features, it's easy to run into having conflicting versions that breaks all types. I think in general supabase team is good at following semver, so I don't think it's high risk to open it up to ranges. Given the infrequent version releases for this repo, it makes even more sense imho to open it up more.

**Comment by psteinroe** [comment]
> The opts parameter carries around react-query options to supabase. There's no splitting or sanitisation happening it seems, but I don't understand why types don't catch that (don't have too much time to dig now). In general, I think what's much better to add supabase options under e.g. opts.postgrestOptions or opts.clientQueryOptions or equivalent. To easily type and split them. From experience, inlining two configs is often more work that it's worth, and becomes brittle easily.

I understand your point, but I don't see a reason to change that at the moment. It makes life easier when implementing and the dx is also better (although that's subjective, you might feel different about it).

> I'm not sure how I feel about version pinning for @supabase/postgrest-js & @supabase/supabase-js – if you wan't to use the latest Supabase features, it's easy to run into having conflicting versions that breaks all types. I think in general supabase team is good at following semver, so I don't think it's high risk to open it up to ranges. Given the infrequent version releases for this repo, it makes even more sense imho to open it up more.

unfortunately, this is not the case. the supabase team does changes to internal types quite frequently in minor releases. this is why pinning is important. renovate is usually updating it for us, but in some cases an update result in type errors and manual work is required. 

anyways, thanks for the contribution!

**Comment by psteinroe** [comment]
funny enough, you can see in the CI why pinning is important: types break with the update. can you please undo the supabase update? would like to split it up into two prs.

**Comment by psteinroe** [comment]
also: added a (now failing) test for this here https://github.com/psteinroe/supabase-cache-helpers/pull/378

**Comment by lauri865** [comment]
> I understand your point, but I don't see a reason to change that at the moment. It makes life easier when implementing and the dx is also better (although that's subjective, you might feel different about it).

I also used to think it's a great, before I built a component library :)

It works until there's a conflict between options keys between react-query and supabase, or if supabase starts validating options – then you'd have to do it anyways (or come up with custom mappings, which is even worse). Inline enough of properties, and you'll make the DX also worse, because the developer needs to start thinking what is the option for now – am I passing it to react-query or to supabase? Plus maintainability woes.

Anyways, it's not an urgent topic by any means, but one that could become relevant based on external factors.

**Comment by psteinroe** [comment]
> The test is for updates and not upserts though?

yes, because there is already one for upserts that passes... can you double check?

**Pull request closed without merging**
