### PR TITLE
test: many-to-many revalidateRelations test

### PR DESCRIPTION
**Pull request by Keithcat767**
Related to this issue: https://github.com/psteinroe/supabase-cache-helpers/issues/390

This PR includes a failing test for revalidateRelations when dealing with many-to-many relationships and a junction table. This includes a new migrations that adds two new tables: `address_book` and `address_book_contact`. `address_book` and `contacts` have a many-to-many relationship through the new junction table `address_book_contact`. In the test, we get a specific address book and all the related contacts that have access to it. When we remove a contact from the address book, we need to invalidate the original address book query cache so it will be re-fetched.

Hope this helps!

### CODE REVIEW

**Comment by psteinroe** [comment]
thanks, that helped a lot @Keithcat767! fixed two bugs thanks to your issue + test. I didn't want to fiddle in your pr, but would you be so kind and remove the comments etc from this so we can just merge the test?

**Comment by Keithcat767** [comment]
> thanks, that helped a lot @Keithcat767! fixed two bugs thanks to your issue + test. I didn't want to fiddle in your pr, but would you be so kind and remove the comments etc from this so we can just merge the test?

Awesome! Glad to hear it! Yeah, I can remove those and clean up the test a tiny bit in an hour or so.

**Comment by psteinroe** [comment]
> > thanks, that helped a lot @Keithcat767! fixed two bugs thanks to your issue + test. I didn't want to fiddle in your pr, but would you be so kind and remove the comments etc from this so we can just merge the test?
> 
> Awesome! Glad to hear it! Yeah, I can remove those and clean up the test a tiny bit in an hour or so.

great, thanks! just merged the pr that fixes this, so your test should be green.

**Comment by Keithcat767** [comment]
> > > thanks, that helped a lot @Keithcat767! fixed two bugs thanks to your issue + test. I didn't want to fiddle in your pr, but would you be so kind and remove the comments etc from this so we can just merge the test?
> > 
> > 
> > Awesome! Glad to hear it! Yeah, I can remove those and clean up the test a tiny bit in an hour or so.
> 
> great, thanks! just merged the pr that fixes this, so your test should be green.

Confirmed the test passes when I update the import in useDeleteItem, but it looks like we will need a new build of core to get the test to pass on its own. The useDeleteItem hook relies on the built core package it looks like:

```
import {
  deleteItem,
  DeleteItemOperation,
} from '@supabase-cache-helpers/postgrest-core';
```

**Comment by psteinroe** [comment]
@Keithcat767 its actually simpler - the migration just needs an on delete cascade so that we can cleanup the test by deleting the contacts properly. otherwise it interferes with the other test. added it for you, should pass now! thanks again.

**Comment by Keithcat767** [comment]
> @Keithcat767 its actually simpler - the migration just needs an on delete cascade so that we can cleanup the test by deleting the contacts properly. otherwise it interferes with the other test. added it for you, should pass now! thanks again.

Doh! Good catch!

**Pull request merged**
