### PR TITLE
Upgrade nextra doc to v3.2

### PR DESCRIPTION
**Pull request by damien-schneider**
### Changes
- **Meta File:** Rename `_meta.json` to `_meta.ts`.
- **Imports:** Update import paths from `"nextra-theme-docs"` to `"nextra/components"`.
- **Components:** Replace `<Tab>` with `<Tabs.Tab>`.

### pnpm Version
- **Used:** pnpm v9 to avoid installing v8 locally.
- **Potential Issue:** Vercel might detect a `pnpm-lock.yaml` version mismatch, causing build errors.

**Options:**
1. **Upgrade to pnpm v9 (Preferred)**
   - Update repository to use pnpm v9.
   - Run `pnpm install` to regenerate `pnpm-lock.yaml`.
2. **Revert to pnpm v8**
   - Install pnpm v8 locally.
   - Delete `pnpm-lock.yaml` and run `pnpm install`.

If you prefer to use pnpm v8, I would prefer you to commit on my branch (I've gived you the rights) so that I don't have to install the v8 :)
Please let me know your preferred approach.

### CODE REVIEW

**Comment by damien-schneider** [comment]
@psteinroe Should I make changes for this PR to be accepted? I want to do some changes to the doc but prefer to wait this PR to be accepted before :)

**Comment by psteinroe** [comment]
> @psteinroe Should I make changes for this PR to be accepted? I want to do some changes to the doc but prefer to wait this PR to be accepted before :)

this is a huge pr, and upgrading to pnpm v9 should not be part of this imo. if you are not able to run pnpm v9 locally, I will need to check this out and push the new lock file. will do it in a few days.

**Comment by psteinroe** [comment]
> I agree that the upgrade of pnpm shouldn't be done in this PR, I've finally achieve to install back the pnpm-lock with pnpm@8.15.8.
> 
> I'll probably make a PR to upgrade to latest version of pnpm if you agree

thanks!

**Comment by damien-schneider** [comment]
I've fixed the formatting, the test should pass now.

**Comment by damien-schneider** [comment]
Could we merge this ?

**Comment by psteinroe** [comment]
@damien-schneider sorry for the delay! merging

**Pull request merged**
